<!--INICIO DE CODIGO DE PHP-->
<?php
      include "php_inv/conexion.php";
//CONDICION QUE SI ES DIFERENTE A EMPTY OSEA QUE ESTE VACIO Y QUE RECOJA EL ID OBTENIENDOLO POR UN GET
if (!empty($_GET["id"])) {
    //SE ALMACENAN EN UNA VARIABLE Y SE RECOGEN CON SU METODO GET Y LLAMANDOLES POR SU NAME 
    $id=$_GET["id"];
    //VARIABLE $SQL LLAMANDO A LA $CONEXION POR MEDIO DL QUERY CON LA FUNCION DE BASE DE DATOS (DELETE) LLAMANDO LA TABLA INVENTARIO CON EL NAME QUE SEA ELIMINADO
    //EN LA VARIABLE PREVIAMENTE LLAMADA DONDE WHERE ID ES IGUAL AL ID
    $sql=$conexion->query(" delete from inventario where id=$id ");
    //PARA VERIFICAR QUE EL PRODUCTO SE HAYA BORRADO CORRECTAMENTE ES LA CONDICION SI LA VARIABLE $SQL ES IGUAL A 1 
    //OSEA QUE LEE AL MENOS A 1 LINEA SE MANDA MENSAJE DENTRO DE UN DIV PARA REFLEJAR EL MOVIMIENTO SEA CORRECTO O DE ERROR EN ELIMINAR PRODUCTO DE CADA CONDICION
    if ($sql==1) {
        echo '<div class="alert alert-success">PRODUCTO ELIMINADO CORRECTAMENTE</div>';
    }else{
        echo '<div class="alert alert-danger">ERROR AL ELIMINAR</div>';
    }    
}


?>